### ISSUE TITLE
Windows clone error.

### ISSUE THREAD

**Issue by aloedawn** [shfd27/DiscordBot#1]
Windows doesn't support '.' on the folder name.
Please consider changing the name of the path.
------------------------
```
error: invalid path 'old_ver/music_1.0.0./music.py'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

**Comment by shfd27** [comment]
Windows can not use dot at the end of the folder name.
Just ignore **old_ver**. It will be fixed later.

**Comment by aloedawn** [comment]
Ok, Thank you for your answer.
